/*
 * Copyright 2023 Khalid BOURR
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 package com.example.B2XKlaim.Service.codeGenerator;

 import java.io.FileNotFoundException;
 import java.io.UnsupportedEncodingException;
 import java.lang.reflect.Method;
 import java.util.ArrayList;
 import java.util.Collections;
 import java.util.Comparator;
 import java.util.HashMap;
 import java.util.HashSet;
 import java.util.Iterator;
 import java.util.List;
 import java.util.Map;
 import java.util.Objects;
 import java.util.Set;
 import java.util.stream.Collectors;

 import com.example.B2XKlaim.Service.bpmnElements.BpmnElement;
import com.example.B2XKlaim.Service.bpmnElements.BpmnElements;
import com.example.B2XKlaim.Service.bpmnElements.activities.CLA;
import com.example.B2XKlaim.Service.bpmnElements.activities.ESP;
import com.example.B2XKlaim.Service.bpmnElements.activities.ST;
import com.example.B2XKlaim.Service.bpmnElements.events.MEE;
import com.example.B2XKlaim.Service.bpmnElements.events.MIC;
import com.example.B2XKlaim.Service.bpmnElements.events.MIT;
import com.example.B2XKlaim.Service.bpmnElements.events.MSE;
import com.example.B2XKlaim.Service.bpmnElements.events.NEE;
import com.example.B2XKlaim.Service.bpmnElements.events.NSE;
import com.example.B2XKlaim.Service.bpmnElements.events.SEE;
import com.example.B2XKlaim.Service.bpmnElements.events.SIC;
import com.example.B2XKlaim.Service.bpmnElements.events.SIT;
import com.example.B2XKlaim.Service.bpmnElements.events.SSE;
import com.example.B2XKlaim.Service.bpmnElements.events.TCE;
import com.example.B2XKlaim.Service.bpmnElements.events.TEE;
import com.example.B2XKlaim.Service.bpmnElements.events.TSE;
import com.example.B2XKlaim.Service.bpmnElements.flows.MessageFLow;
import com.example.B2XKlaim.Service.bpmnElements.flows.SQ;
import com.example.B2XKlaim.Service.bpmnElements.gateways.AND;
import com.example.B2XKlaim.Service.bpmnElements.gateways.EB;
import com.example.B2XKlaim.Service.bpmnElements.gateways.LP;
import com.example.B2XKlaim.Service.bpmnElements.gateways.XOR;
import com.example.B2XKlaim.Service.bpmnElements.objects.DO;
import com.example.B2XKlaim.Service.bpmnElements.objects.Field;
import java.util.Arrays;
import com.example.B2XKlaim.Service.bpmnElements.objects.pool.Collab;
import com.example.B2XKlaim.Service.bpmnElements.objects.pool.MIPL;
import com.example.B2XKlaim.Service.bpmnElements.objects.pool.PL;

import lombok.extern.slf4j.Slf4j;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

 
 
 /**
  * Translates BPMN elements into XKlaim code using the Visitor pattern.
  */
 @Slf4j // for logging
 public class BPMNTranslator implements Visitor {
 
     // --- Member Variables ---
     private final BpmnElements bpmnElements; // Reference to the parsed model container
     private final Map<String, Set<String>> requiredParticipantRefs; // Analysis results
     private final Map<String, PL> participantsMap; // Quick lookup for participants by ID
 
     // State for the current process being translated
     private String currentParticipantId = null;
     private PL currentParticipant = null;
     // Maps required Participant Name -> Generated Local Variable Name for the current process
     private Map<String, String> currentParamMap = new HashMap<>();
     // Auxiliary proc definitions generated by AND gateway branches
     private List<String> auxiliaryProcs = new ArrayList<>();
     // Persistent map of all AND branch procs (survives per-participant reset)
     private Map<String, List<String>> allAndBranchProcs = new HashMap<>();

     public List<String> getAuxiliaryProcs() {
         return new ArrayList<>(auxiliaryProcs);
     }

     public Map<String, List<String>> getAllAndBranchProcs() {
         return new HashMap<>(allAndBranchProcs);
     }

     /**
      * Merges AND branch procs harvested from another translator
      */
     public void mergeAndBranchProcs(Map<String, List<String>> other) {
         if (other == null || other.isEmpty()) return;
         this.allAndBranchProcs.putAll(other);
     }

     // --- Constructor ---
 
     public BPMNTranslator(BpmnElements bpmnElements) {
         Objects.requireNonNull(bpmnElements, "BpmnElements object cannot be null");
         this.bpmnElements = bpmnElements;
         this.requiredParticipantRefs = bpmnElements.getRequiredParticipantRefs();
         this.participantsMap = bpmnElements.getParticipantsMap();
         log.info("BPMNTranslator initialized. Required Refs: {}", this.requiredParticipantRefs);
     }
 
     // --- Helper Methods ---
 
     private String getParticipantName(String participantId) {
         PL participant = participantsMap.get(participantId);
         return (participant != null) ? participant.getName() : "UNKNOWN_ID_" + participantId;
     }
 
     private String generateLocalVarName(String participantName) {
         if (participantName == null || participantName.isEmpty()) {
             return "unknown_loc";
         }
         return participantName.replaceAll("[^a-zA-Z0-9_]", "").toLowerCase() + "_loc";
     }

     public String translateProcessBody(List<BpmnElement> startEvents) throws FileNotFoundException, UnsupportedEncodingException {
         StringBuilder bodyCode = new StringBuilder();
         for (BpmnElement startEvent : startEvents) {
             bodyCode.append(translateProcessBody(startEvent));
         }
         return bodyCode.toString();
     }

     private void resetProcessState() {
         this.currentParticipantId = null;
         this.currentParticipant = null;
         if (this.currentParamMap == null) { this.currentParamMap = new HashMap<>(); }
         this.currentParamMap.clear();
         this.auxiliaryProcs.clear();
         log.trace("Process state reset.");
     }
 
      private void setupProcessState(PL participant) {
          resetProcessState();
          Objects.requireNonNull(participant, "Participant cannot be null for setupProcessState");
          currentParticipant = participant;
          currentParticipantId = participant.getId();
          log.debug("Setting up state for Participant: '{}' (ID: {})", participant.getName(), participant.getId());
 
          Set<String> neededRefs = requiredParticipantRefs.get(currentParticipantId);
          if (neededRefs != null && !neededRefs.isEmpty()) {
              log.debug("Participant '{}' requires references to IDs: {}", participant.getName(), neededRefs);
              for (String neededParticipantId : neededRefs) {
                  String participantName = getParticipantName(neededParticipantId);
                  if (!participantName.startsWith("UNKNOWN_ID")) {
                      String localVarName = generateLocalVarName(participantName);
                      currentParamMap.put(participantName, localVarName);
                      log.trace("Mapping required participant '{}' to local var '{}'", participantName, localVarName);
                  } else {
                       log.warn("Could not find name for required participant ID: {}. Cannot generate parameter.", neededParticipantId);
                  }
              }
          } else {
               log.debug("Participant '{}' requires no external references.", participant.getName());
          }
      }
 

     private Method getVisitMethod(Class<? extends BpmnElement> elementType) {
          Class<?> currentClass = elementType;
          while (currentClass != null && BpmnElement.class.isAssignableFrom(currentClass)) {
               try {
                   return this.getClass().getMethod("visit", currentClass);
               } catch (NoSuchMethodException e) {
                   currentClass = currentClass.getSuperclass();
                   if (currentClass == Object.class || currentClass == null) break;
               }
          }
          log.trace("No specific visit method found in BPMNTranslator for {} or its superclasses.", elementType.getName());
           try {
                 return this.getClass().getMethod("visit", BpmnElement.class); // Example fallback
             } catch (NoSuchMethodException e) {
                  log.warn("No visit method found for {} or its hierarchy.", elementType.getName());
                  return null;
             }
     }
 
    /**
     * Translates the body of a process starting from a given element,
     * traversing sequence flows recursively/iteratively. Delegates complex
     * control flow (gateways) to specific visit methods.
     *
     * @param startElement The element to start traversal from (usually a Start Event).
     * @return The generated XKlaim code string for the process body path.
     */
    public String translateProcessBody(BpmnElement startElement)
    throws FileNotFoundException, UnsupportedEncodingException {

        StringBuilder bodyCode = new StringBuilder();
        Set<BpmnElement> visitedElements = new HashSet<>();
        BpmnElement currentElement = startElement;

        while (currentElement != null && !visitedElements.contains(currentElement)) {
            visitedElements.add(currentElement);
            log.trace(">>> [Translator Traversal] Visiting Element: {} ({})", 
                    currentElement.getId(), currentElement.getClass().getSimpleName());

            Method visitMethod = getVisitMethod(currentElement.getClass());
            String elementResult = null;

            if (visitMethod != null) {
                try {
                    // 1. Visit the current element
                    elementResult = (String) visitMethod.invoke(this, currentElement);

                    if (elementResult != null) {
                        bodyCode.append(elementResult);
                    } else {
                        log.warn("Visit method for {} returned null.", currentElement.getId());
                    }

                    // 2. Always attempt to follow outgoing edge unless explicitly handled by the visit method
                    String outgoingSequenceFlowId = currentElement.getOutgoingEdge();
                    log.trace(">>> [Translator Traversal] Outgoing Edge from {}: {}", 
                            currentElement.getId(), outgoingSequenceFlowId);

                    if (outgoingSequenceFlowId != null && !outgoingSequenceFlowId.isEmpty()) {
                        BpmnElement sequenceFlowElement = this.bpmnElements.getElementById(outgoingSequenceFlowId);
                        log.trace(">>> [Translator Traversal] Sequence Flow Element Found: {} ({})", 
                                (sequenceFlowElement != null ? sequenceFlowElement.getId() : "null"),
                                (sequenceFlowElement != null ? sequenceFlowElement.getClass().getSimpleName() : "null"));

                        if (sequenceFlowElement instanceof SQ) {
                            // Visit SQ (sequence flow)
                            Method sqVisitMethod = getVisitMethod(SQ.class);
                            String sqResult = null;
                            if (sqVisitMethod != null) {
                                sqResult = (String) sqVisitMethod.invoke(this, sequenceFlowElement);
                            } else {
                                log.warn("No visit method for SQ {}", outgoingSequenceFlowId);
                            }

                            if (sqResult != null) {
                                bodyCode.append(sqResult);
                            }

                            // Move to the next element after the sequence flow
                            currentElement = this.bpmnElements.getElementAfterSequenceFlow(outgoingSequenceFlowId);
                        } else {
                            log.warn("Element {} outgoing edge {} is not an SQ element or not found.",
                                    currentElement.getId(), outgoingSequenceFlowId);
                            currentElement = null; // Stop
                        }
                    } else {
                        // No outgoing edge -> End of this path
                        log.trace("Element {} has no outgoing edge. Ending traversal.",
                                currentElement.getId());
                        currentElement = null; // Stop
                    }

                } catch (Exception e) {
                    log.error("Error during translation processing for element {}: {}",
                            (currentElement != null ? currentElement.getId() : "unknown"),
                            e.getMessage(), e);
                    currentElement = null; // Stop traversal on error
                }
            } else {
                log.warn("No visit method found for element {} (Class: {}). Skipping.",
                        currentElement.getId(), currentElement.getClass().getSimpleName());
                currentElement = null;
            }
        }

        if (currentElement != null && visitedElements.contains(currentElement)) {
            log.debug("Stopping traversal for element {} - already visited in this path (potential loop).",
                    currentElement.getId());
        }

        log.debug("translateProcessBody result: [\n{}]", bodyCode.toString());
        return bodyCode.toString();
        }
        
 
     // --- Visitor Methods ---
 
    /**
     * Entry point for translating a collaboration. Generates the network definition
     * and then iterates through participants (sorted by name) to generate their
     * process definitions, including calls to Event Sub-Processes.
     */
    @Override
    public String visit(Collab collab) throws FileNotFoundException, UnsupportedEncodingException {
        StringBuilder collabCode = new StringBuilder();
        collabCode.append(String.format("net %s physical \"localhost:9999\" {\n\n", collab.getId()));

        List<PL> participants = bpmnElements.getElementsByType(PL.class);

        // Sort participants by name for consistent output order
        if (participants != null) {
             participants.sort(Comparator.comparing(PL::getName, String.CASE_INSENSITIVE_ORDER));
             log.debug("Sorted participants by name: {}", participants.stream().map(PL::getName).collect(Collectors.toList()));
        }

        // Phase 1: Generate node definitions
        log.info("Generating node definitions (sorted)...");
        for (PL participant : participants) {
             if (participant == null) continue;
            setupProcessState(participant);
            collabCode.append(participant.accept(this)); // Calls visit(PL)
        }
        resetProcessState();
        collabCode.append("}\n"); // Close net block

        // Phase 2: Generate process definitions
        log.info("Generating process definitions (sorted)...");
        for (PL participant : participants) {
             if (participant == null) continue;
            setupProcessState(participant); // Sets up currentParamMap

            // Generate proc signature
            String procParamsString = "";
            if (!currentParamMap.isEmpty()) {
                procParamsString = currentParamMap.values().stream()
                                .map(varName -> "Locality " + varName)
                                .sorted()
                                .collect(Collectors.joining(", "));
            }
            collabCode.append(String.format("\nproc %s(%s) {\n",
                    participant.getProcessName(),
                    procParamsString));

            log.debug("Looking for Event Sub-Processes in process {}", participant.getProcessId());
            List<ESP> eventSubProcesses = bpmnElements.getEventSubProcessesForProcess(participant.getProcessId());
            if (eventSubProcesses != null && !eventSubProcesses.isEmpty()) {
                log.debug("Found {} ESPs for process {}. Generating eval calls.", eventSubProcesses.size(), participant.getProcessId());
                for (ESP esp : eventSubProcesses) {
                    // Instead of including full ESP code, just add an eval call
                    String espName = esp.getName() != null && !esp.getName().isEmpty() ? esp.getName() : esp.getId();
                    collabCode.append(String.format("  eval(new %s())@self\n\n", espName));
                }
            }

            // Generate the main process body using the traversal helper method
            List<BpmnElement> startEvents = bpmnElements.findStartEventsForProcess(participant.getProcessId());

            if (startEvents == null || startEvents.isEmpty()) {
                 log.warn("No main start event found for process '{}' (ID: {}). Process body will be empty (excluding ESPs).", participant.getProcessName(), participant.getProcessId());
                 collabCode.append("\n\t// No main start event found for this process.\n");
            } else {
                log.debug("Found {} main start event(s) for process '{}'. Translating body...", startEvents.size(), participant.getProcessName());
                for (BpmnElement startEvent : startEvents) {
                    // Call the traversal method starting from the start event
                    collabCode.append(this.translateProcessBody(startEvent)); // Append the generated body
                }
            }

            collabCode.append("}\n"); // Close proc definition

            resetProcessState();
        }

        log.debug("visit(Collab) result:\n{}", collabCode.toString());
        return collabCode.toString();
    }

 
     @Override
     public String visit(PL pl) throws FileNotFoundException, UnsupportedEncodingException {
         if (currentParticipant == null || !Objects.equals(currentParticipant.getId(), pl.getId())) {
              log.error("Visiting PL '{}' but translator state is not set up correctly! Expected state for {}.", pl.getName(), pl.getId());
              setupProcessState(pl);
         }
 
         String participantName = pl.getName();
         String processName = pl.getProcessName();
 
         String argsString = ""; // Default to empty args string INSIDE parentheses
         if (!currentParamMap.isEmpty()) {
             Set<String> neededRefsIds = requiredParticipantRefs.get(pl.getId());
              if (neededRefsIds != null) {
                  List<String> neededNames = neededRefsIds.stream()
                          .map(this::getParticipantName)
                          .filter(name -> !name.startsWith("UNKNOWN_ID"))
                          .sorted()
                          .collect(Collectors.toList());
                  // Join names with ", " only if neededNames is not empty
                  if (!neededNames.isEmpty()) {
                     argsString = String.join(", ", neededNames);
                  }
              }
         }
 
         // Log using the inner arguments string
         log.info(">>> visit(PL): Formatting node. ID='{}', Name='{}', Process='{}', Args='{}'",
                  pl.getId(), participantName, processName, argsString);
 
         // Check for null names before formatting
         if (participantName == null || processName == null) {
              log.error(">>> visit(PL) Error: Participant Name ('{}') or Process Name ('{}') is null for PL ID: {}",
                       participantName, processName, pl.getId());
              return "/* ERROR: Participant Name or Process Name missing for "+pl.getId()+" */\n";
         }
 
         String dataObjectsBlock = translateDataObjectsForProcess(pl.getProcessId());

         // Updated nodeTemplate always includes parentheses for eval
         String nodeTemplate = "\tnode %s {\n" +
                 "%s" +
                 "\t\teval(new %s(%s))@self\n" +
                 "\t}\n";
         // Format using the inner arguments string
         String result = String.format(nodeTemplate, participantName, dataObjectsBlock, processName, argsString);
 
         log.info(">>> visit(PL) Returning: [\n{}]", result);
         return result;
     }
  
     @Override
     public String visit(NSE nse) {
         log.trace("Visiting NSE: {}", nse.getId());
         return String.format("out('%s')@self\n", nse.getOutgoingEdge());
     }
 
     @Override
     public String visit(MSE mse) {
         log.trace("Visiting MSE: {} (Msg: {})", mse.getId(), mse.getMessageId());
         return formatMessageCatch(mse.getMessageId(), mse.getTargetDataRef(), mse.getOutgoingEdge());
     }
 
     @Override
     public String visit(SSE sse) {
          log.trace("Visiting SSE: {} (Sig: {})", sse.getId(), sse.getSignalId());
          String senderName = sse.getSignalSenderName();
          String targetLocation = "self";
 
          if (senderName != null && !senderName.equalsIgnoreCase("self") && currentParamMap.containsKey(senderName)) {
               targetLocation = currentParamMap.get(senderName);
          } else if (senderName != null && !senderName.equalsIgnoreCase("self")) {
               log.warn("SSE {}: Reading from sender '{}' but no Local param found. Using raw name.", sse.getId(), senderName);
               targetLocation = senderName;
          } else { targetLocation = "self"; }
 
          return String.format("read('%s' %s)@%s\nout('%s')@self\n",
                  sse.getSignalId(), "", targetLocation, sse.getOutgoingEdge());
     }
 
     @Override
     public String visit(MIC mic) {
         log.trace("Visiting MIC: {} (Msg: {})", mic.getId(), mic.getMessageId());
         return formatMessageCatch(mic.getMessageId(), mic.getTargetDataRef(), mic.getOutgoingEdge());
     }


     private String formatMessageCatch(String messageId, String targetDataRef, String outgoingEdge) {
         DO target = (targetDataRef == null) ? null
                 : (DO) bpmnElements.getElementById(targetDataRef);
         if (target == null || target.getFields() == null || target.getFields().isEmpty()) {
             return String.format("in('%s')@self\nout('%s')@self\n", messageId, outgoingEdge);
         }
         String dataName = target.getName();
         List<Field> fields = target.getFields();

         StringBuilder sb = new StringBuilder();
         sb.append("in('").append(messageId).append("'");
         for (Field f : fields) {
             sb.append(", var ").append(typeOrObject(f.getType()))
               .append(" ").append(varName(dataName, f.getName()));
         }
         sb.append(")@self\n");

         sb.append("in('").append(dataName).append("'");
         for (Field f : fields) {
             sb.append(", var ").append(typeOrObject(f.getType()))
               .append(" ").append("dummy_").append(f.getName());
         }
         sb.append(")@self\n");

         sb.append("out('").append(dataName).append("'");
         for (Field f : fields) {
             sb.append(", ").append(varName(dataName, f.getName()));
         }
         sb.append(")@self\n");

         sb.append("out('").append(outgoingEdge).append("')@self\n");
         return sb.toString();
     }

     private static String varName(String dataName, String fieldName) {
         return dataName + "_" + fieldName;
     }

     private static String typeOrObject(String type) {
         return (type == null || type.isEmpty()) ? "Object" : type;
     }
 
     @Override
     public String visit(SIC sic) {
          log.trace("Visiting SIC: {} (Sig: {})", sic.getId(), sic.getSignalId());
          String senderName = sic.getSignalSenderName();
          String targetLocation = "self";
 
          if (senderName != null && !senderName.equalsIgnoreCase("self") && currentParamMap.containsKey(senderName)) {
               targetLocation = currentParamMap.get(senderName);
          } else if (senderName != null && !senderName.equalsIgnoreCase("self")) {
               log.warn("SIC {}: Reading from sender '{}' but no Local param found. Using raw name.", sic.getId(), senderName);
               targetLocation = senderName;
          } else { targetLocation = "self"; }
 
         return String.format("read('%s' %s)@%s\nout('%s')@self\n",
                  sic.getSignalId(), "", targetLocation, sic.getOutgoingEdge());
     }
 
     @Override
     public String visit(MIT mit) {
         log.trace("Visiting MIT: {} (Msg: {})", mit.getId(), mit.getMessageId());
         String targetLocation = resolveReceiverLocation(mit.getMessageFlow(), mit.getId(), "MIT");
         return formatMessageThrow(mit.getMessageId(), mit.getSourceDataRefs(),
                 mit.getPayload(), targetLocation, mit.getOutgoingEdge());
     }
 
     @Override
     public String visit(SIT sit) {
         log.trace("Visiting SIT: {} (Sig: {})", sit.getId(), sit.getSignalId());
         return String.format("out('%s')@self\nval SIGNAL_DURATION = 1000 // Adjust the signal duration as needed\nThread.sleep(SIGNAL_DURATION)\nin('%s')@self\nout('%s')@self\n",
                 sit.getSignalId(), sit.getSignalId(), sit.getOutgoingEdge());
     }
 
     @Override
     public String visit(NEE nee) {
         log.trace("Visiting NEE: {}", nee.getId());
         return "\n";
     }
 
     @Override
     public String visit(MEE mee) {
          log.trace("Visiting MEE: {} (Msg: {})", mee.getId(), mee.getMessageId());
          String targetLocation = resolveReceiverLocation(mee.getMessageFlow(), mee.getId(), "MEE");
          return formatMessageThrow(mee.getMessageId(), mee.getSourceDataRefs(),
                  mee.getPayload(), targetLocation, null) + "\n";
     }

     private String resolveReceiverLocation(MessageFLow flow, String eventId, String eventKind) {
         String receiverName = (flow != null) ? flow.getReceiverName() : null;
         if (receiverName == null) {
             log.warn("{} {}: Cannot determine receiver. Target set to 'null'.", eventKind, eventId);
             return "null";
         }
         if (currentParamMap.containsKey(receiverName)) {
             return currentParamMap.get(receiverName);
         }
         log.warn("{} {}: Sending to receiver '{}' but no Local param found. Using raw name.",
                 eventKind, eventId, receiverName);
         return receiverName;
     }

     private String formatMessageThrow(String messageId, List<String> sourceDataRefs,
                                       List<Field> payload, String target, String outgoingEdge) {
         StringBuilder sb = new StringBuilder();

         if (sourceDataRefs != null) {
             for (String ref : sourceDataRefs) {
                 DO source = (DO) bpmnElements.getElementById(ref);
                 if (source == null) continue;
                 sb.append("read('").append(source.getName()).append("'");
                 if (source.getFields() != null) {
                     for (Field f : source.getFields()) {
                         sb.append(", var ").append(typeOrObject(f.getType()))
                           .append(" ").append(varName(source.getName(), f.getName()));
                     }
                 }
                 sb.append(")@self\n");
             }
         }

         sb.append("out('").append(messageId).append("'");
         if (payload != null) {
             for (Field f : payload) {
                 sb.append(", ").append(f.getName());
             }
         }
         sb.append(")@").append(target).append("\n");

         if (outgoingEdge != null && !outgoingEdge.isEmpty()) {
             sb.append("out('").append(outgoingEdge).append("')@self\n");
         }
         return sb.toString();
     }
 
      @Override
      public String visit(SEE see) {
          log.trace("Visiting SEE: {} (Sig: {})", see.getId(), see.getSignalId());
          return String.format("out('%s')@self\nval SIGNAL_DURATION = 1000 // Adjust the signal duration as needed\nThread.sleep(SIGNAL_DURATION)\nin('%s')@self\n\n",
                  see.getSignalId(), see.getSignalId());
      }
 
      @Override
      public String visit(TSE tse) throws FileNotFoundException, UnsupportedEncodingException {
         log.trace("Visiting TSE: {} (Duration: {})", tse.getId(), tse.getDuration());
         return String.format("Thread.sleep(%d)\nout('%s')@self\n", tse.getDuration(), tse.getOutgoingEdge());
      }
 
      @Override
      public String visit(TCE tce) throws FileNotFoundException, UnsupportedEncodingException {
         log.trace("Visiting TCE: {} (Duration: {})", tce.getId(), tce.getDuration());
          return String.format("Thread.sleep(%d)\nout('%s')@self\n", tce.getDuration(), tce.getOutgoingEdge());
      }
 
     @Override
     public String visit(TEE tee) throws FileNotFoundException, UnsupportedEncodingException {
         log.trace("Visiting TEE (Terminate End Event): {}", tee.getId());
         return "// Terminate Event\nexit @ self\n";
     }
 
     // --- Sequence Flow ---
     @Override
     public String visit(SQ sq) {
         log.trace("Visiting SQ: {}", sq.getId());
         // This generates the "in" for the completed sequence flow token
         return String.format("in('%s')@self\n\n", sq.getId());
     }
 
 
     @Override
     public String visit(CLA cla) throws FileNotFoundException, UnsupportedEncodingException {
          log.trace("Visiting CLA: {} (Calls: {})", cla.getId(), cla.getCalledProcess());
          String calledProcess = cla.getCalledProcess();
          String outgoingEdge = cla.getOutgoingEdge(); // Get the outgoing edge ID
 
         if (calledProcess == null || calledProcess.isEmpty()) {
              log.error("Call Activity {} is missing the 'calledElement' attribute.", cla.getId());
              return "// ERROR: Call Activity missing calledElement\n";
         }
         if (outgoingEdge == null || outgoingEdge.isEmpty()) {
             log.error("Call Activity {} ({}) has no outgoing edge defined. Cannot generate proper eval.", cla.getId(), calledProcess);
              // Return only eval without out, but this breaks flow
              return String.format("eval(new %s(/* ERROR: Missing outgoing edge */))@self\n", calledProcess);
         }
 
          return String.format("eval(new %s('%s'/* TODO: Pass other necessary args */))@self\n",
                               calledProcess,
                               outgoingEdge);
     }
 
     @Override
     public String visit(ESP esp) throws FileNotFoundException, UnsupportedEncodingException {
         StringBuilder sb = new StringBuilder();
         
         // Create a proc with the ESP ID or name
         String espName = esp.getName() != null && !esp.getName().isEmpty() ? esp.getName() : esp.getId();
         sb.append(String.format("proc %s() {\n", espName));
         
         // Find the start event among internal elements
         BpmnElement startEvent = null;
         for (BpmnElement element : esp.getInternalElements()) {
             if (element instanceof com.example.B2XKlaim.Service.bpmnElements.events.NSE ||
                 element instanceof com.example.B2XKlaim.Service.bpmnElements.events.MSE ||
                 element instanceof com.example.B2XKlaim.Service.bpmnElements.events.SSE ||
                 element instanceof com.example.B2XKlaim.Service.bpmnElements.events.TSE) {
                 startEvent = element;
                 break;
             }
         }
         
         if (startEvent != null) {
             // Generate process body starting from the start event, following sequence flows
             String processBody = translateProcessBody(startEvent);
             
             // Add indentation to each line
             String[] lines = processBody.split("\\r?\\n");
             for (String line : lines) {
                 if (!line.trim().isEmpty()) {
                     sb.append("  ").append(line).append("\n");
                 }
             }
         } else {
             log.warn("No start event found for Event Sub-Process {}", espName);
         }
         
         sb.append("}\n");
         return sb.toString();
     }
     
     @Override
     public String visit(AND and) throws FileNotFoundException, UnsupportedEncodingException {
        StringBuilder s = new StringBuilder();

        List<String> branchProcNames = new ArrayList<>();
        List<String> branchLastEdges = new ArrayList<>();
        int branchIndex = 0;

        for (Map.Entry<Integer, List<String>> entry : and.getFlowElementMap().entrySet()) {
            List<String> branchElements = entry.getValue();
            String branchProcName = String.format("AND_%s_Branch%d", and.getId(), branchIndex);
            branchProcNames.add(branchProcName);

            // Build the branch proc body
            StringBuilder branchBody = new StringBuilder();
            String lastEdge = null;
            for (int i = 0; i < branchElements.size(); i++) {
                String elementId = branchElements.get(i);
                BpmnElement element = bpmnElements.getElementById(elementId);
                if (element == null) {
                    log.warn("AND gateway: element '{}' not found, skipping", elementId);
                    continue;
                }
                branchBody.append("  ").append(element.accept(this));

                if (i < branchElements.size() - 1) {
                    BpmnElement sequence = bpmnElements.getElementById(element.getOutgoingEdge());
                    if (sequence != null) {
                        branchBody.append("  ").append(sequence.accept(this));
                    }
                }
                if (i == branchElements.size() - 1) {
                    lastEdge = element.getOutgoingEdge();
                }
            }
            

            branchLastEdges.add(lastEdge);

            // Optimize the branch body (remove redundant out/in pairs, etc.)
            List<String> bodyLines = Arrays.asList(branchBody.toString().split("\\r?\\n"));
            List<String> optimizedLines = Optimizer.optimize(bodyLines);
            String optimizedBody = String.join("\n", optimizedLines);

            // Generate the auxiliary proc definition
            StringBuilder procDef = new StringBuilder();
            procDef.append(String.format("proc %s() {\n", branchProcName));
            procDef.append(optimizedBody).append("\n");
            procDef.append("}\n");
            auxiliaryProcs.add(procDef.toString());
            allAndBranchProcs.put(branchProcName, Collections.singletonList(procDef.toString()));

            branchIndex++;
        }

        // Generate eval calls to launch branches in parallel
        for (String procName : branchProcNames) {
            s.append(String.format("eval(new %s())@self\n", procName));
        }

        // Generate in() calls to wait for each branch to complete
        for (String edge : branchLastEdges) {
            if (edge != null) {
                s.append(String.format("in('%s')@self\n", edge));
            }
        }

        // Signal AND merge completion
        s.append(String.format("out('%s')@self\n", and.getOutgoingEdge()));

        return s.toString();
    }

    @Override
    public String visit(XOR xor) throws FileNotFoundException, UnsupportedEncodingException {
        StringBuilder s = new StringBuilder();

        Iterator<Map.Entry<String, List<String>>> iterator = xor.getConditionElementMap().entrySet().iterator();

        Map.Entry<String, List<String>> trueBranch = iterator.next();
        Map.Entry<String, List<String>> falseBranch = iterator.hasNext() ? iterator.next() : null;

        // Swap if needed so trueBranch has the condition
        if (falseBranch != null &&
                (trueBranch.getKey() == null || trueBranch.getKey().trim().isEmpty()) &&
                (falseBranch.getKey() != null && !falseBranch.getKey().trim().isEmpty())) {
            Map.Entry<String, List<String>> temp = trueBranch;
            trueBranch = falseBranch;
            falseBranch = temp;
        }

        // Generate if block — use condition if present, otherwise default to "true"
        String condition = (trueBranch.getKey() != null && !trueBranch.getKey().trim().isEmpty())
                ? trueBranch.getKey() : "true";
        s.append(String.format("if(%s){\n", condition));

        for (String elementId : trueBranch.getValue()) {
            BpmnElement element = bpmnElements.getElementById(elementId);
            if (element == null) { log.warn("XOR: element '{}' not found", elementId); continue; }
            s.append("  ").append(element.accept(this));
            BpmnElement sequence = bpmnElements.getElementById(element.getOutgoingEdge());
            if (sequence != null) { s.append("  ").append(sequence.accept(this)); }
        }

        // Generate else block if there's a second branch
        if (falseBranch != null) {
            s.append("} else {\n");
            for (String elementId : falseBranch.getValue()) {
                BpmnElement element = bpmnElements.getElementById(elementId);
                if (element == null) { log.warn("XOR: element '{}' not found", elementId); continue; }
                s.append("  ").append(element.accept(this));
                BpmnElement sequence = bpmnElements.getElementById(element.getOutgoingEdge());
                if (sequence != null) { s.append("  ").append(sequence.accept(this)); }
            }
        }

        s.append("}\n");
        if (xor.getOutgoingEdge() != null) {
            s.append(String.format("out('%s')@self\n", xor.getOutgoingEdge()));
        }

        return s.toString();
    }
 
 
     @Override
     public String visit(LP lp) throws FileNotFoundException, UnsupportedEncodingException {
         StringBuilder sb = new StringBuilder();
         sb.append("while(").append(lp.getCondition()).append("){\n");
         for (String elementId : lp.getFlowElementMap()) {
             BpmnElement element = bpmnElements.getElementById(elementId);
             if (element == null) { log.warn("LP: element '{}' not found", elementId); continue; }
             sb.append(element.accept(this));
             BpmnElement sequence = bpmnElements.getElementById(element.getOutgoingEdge());
             if (sequence != null) { sb.append(sequence.accept(this)); }
         }
         sb.append("}\n");
         sb.append("out('").append(lp.getOutgoingEdge()).append("')@self\n");
         return sb.toString();
     }
 

    /**
     * Visitor implementation for Event-Based Gateway (EB).
     * Three patterns:
     * 1) Messages only        → polling loop with pollTimeout
     * 2) Single message+timer → if(in()@self within d) / else
     * 3) Multi messages+timer → polling loop + elapsed time check for timer
     */
    @Override
    public String visit(EB eb) throws FileNotFoundException, UnsupportedEncodingException {
        StringBuilder s = new StringBuilder();

        // Separate receive paths (message/signal) from the timer path
        List<Map.Entry<String, List<String>>> receivePaths = new ArrayList<>();
        Map.Entry<String, List<String>> timerPath = null;
        long timerDuration = 0;

        for (Map.Entry<String, List<String>> entry : eb.getEventPathMap().entrySet()) {
            if (entry.getValue().isEmpty()) continue;
            BpmnElement event = bpmnElements.getElementById(entry.getValue().get(0));
            if (event instanceof TCE) {
                timerPath = entry;
                timerDuration = ((TCE) event).getDuration();
            } else {
                receivePaths.add(entry);
            }
        }

        boolean hasTimer = timerPath != null;
        boolean singleReceive = receivePaths.size() == 1;

        if (hasTimer && singleReceive) {
            // Pattern 2: single message + timer → if/else with timer duration as within
            Map.Entry<String, List<String>> msgEntry = receivePaths.get(0);
            s.append(String.format("if(%s){\n", buildReceiveCondition(msgEntry.getValue(), timerDuration)));
            appendPathBody(s, msgEntry.getValue());
            s.append("} else {\n");
            appendPathBody(s, timerPath.getValue());
            s.append("}\n");
        } else {
            // Pattern 1 (no timer) or Pattern 3 (multi messages + timer)
            s.append("var boolean eventOccured = false\n");
            if (hasTimer) {
                s.append("var long startTime = System.currentTimeMillis()\n");
            }
            s.append("while(!eventOccured){\n");

            boolean first = true;
            for (Map.Entry<String, List<String>> entry : receivePaths) {
                String condition = buildReceiveCondition(entry.getValue(), 1000);
                if (first) {
                    s.append(String.format("  if(%s){\n", condition));
                    first = false;
                } else {
                    s.append(String.format("  } else if(%s){\n", condition));
                }
                s.append("    eventOccured = true\n");
                appendPathBody(s, entry.getValue());
            }

            if (hasTimer) {
                s.append(String.format("  } else if(System.currentTimeMillis() - startTime >= %d){\n", timerDuration));
                s.append("    eventOccured = true\n");
                appendPathBody(s, timerPath.getValue());
            }

            s.append("  }\n");
            s.append("}\n");
        }

        if (eb.getOutgoingEdge() != null) {
            s.append("out('").append(eb.getOutgoingEdge()).append("')@self\n");
        }

        return s.toString();
    }

    private String buildReceiveCondition(List<String> path, long timeout) {
        BpmnElement event = bpmnElements.getElementById(path.get(0));
        if (event instanceof MIC) {
            return String.format("in('%s')@self within %d", ((MIC) event).getMessageId(), timeout);
        } else if (event instanceof SIC) {
            SIC sic = (SIC) event;
            String location = sic.getSignalSenderName();
            if (currentParamMap != null && currentParamMap.containsKey(location)) {
                location = currentParamMap.get(location);
            }
            return String.format("read('%s')@%s within %d", sic.getSignalId(), location, timeout);
        }
        return String.format("in('%s')@self within %d", path.get(0), timeout);
    }

    private void appendPathBody(StringBuilder s, List<String> path) throws FileNotFoundException, UnsupportedEncodingException {
        for (int i = 1; i < path.size(); i++) {
            BpmnElement element = bpmnElements.getElementById(path.get(i));
            if (element == null) continue;
            s.append("  ").append(element.accept(this));
            String outEdge = element.getOutgoingEdge();
            if (outEdge != null && !outEdge.isEmpty()) {
                BpmnElement sequence = bpmnElements.getElementById(outEdge);
                if (sequence != null) {
                    s.append("  ").append(sequence.accept(this));
                }
            }
        }
    }



     @Override
     public String visit(ST st) {
         log.trace("Visiting ST (as Eval): {} ({})", st.getName(), st.getId());
 
         String processToEval = st.getName(); // Use the Script Task's name as the proc name
         String outgoingEdge = st.getOutgoingEdge(); // Get the outgoing edge ID
 
         if (processToEval == null || processToEval.isEmpty()) {
             log.warn("Script Task {} has no name. Cannot generate eval call.", st.getId());
             if (outgoingEdge != null && !outgoingEdge.isEmpty()) {
                 return String.format("// Script Task with ID {} has no name defined.\nout('%s')@self\n",
                                      st.getId(), outgoingEdge);
             } else {
                  return String.format("// Script Task with ID {} has no name and no outgoing edge.\n", st.getId());
             }
         }
 
         if (outgoingEdge == null || outgoingEdge.isEmpty()) {
              log.error("Script Task {} ({}) has no outgoing edge defined. Cannot generate proper eval.", st.getId(), processToEval);
               return String.format("eval(new %s(/* ERROR: Missing outgoing edge */))@self\n",
                               processToEval);
         }

         return String.format("eval(new %s('%s'/* TODO: Pass other necessary args */))@self\n",
                              processToEval,
                              outgoingEdge);
     }
 
 
     @Override
     public String visit(MIPL mipl) throws FileNotFoundException, UnsupportedEncodingException {
         log.warn("Visiting Multi-Instance Pool (MIPL) - Translation not implemented: {}", mipl.getId());
         return String.format("// Multi-Instance Pool %s translation not implemented\n", mipl.getId());
     }
 
     @Override
     public String visit(DO data) throws FileNotFoundException, UnsupportedEncodingException {
         String dataName = data.getName();
         List<Field> fields = data.getFields();
         StringBuilder sb = new StringBuilder();
         sb.append("out(\"").append(dataName).append("\"");
         if (fields != null) {
             for (Field f : fields) {
                 sb.append(", ").append(initialOrDefault(f));
             }
         }
         sb.append(")@self\n");
         return sb.toString();
     }

     private static String initialOrDefault(Field f) {
         String initial = f.getInitialValue();
         if (initial != null && !initial.isEmpty()) {
             return formatLiteral(initial, f.getType());
         }
         return defaultForType(f.getType());
     }

     private static String formatLiteral(String value, String type) {
         if ("String".equals(type)) {
             String trimmed = value.trim();
             if (trimmed.length() >= 2 && trimmed.startsWith("\"") && trimmed.endsWith("\"")) {
                 return trimmed;
             }
             return "\"" + value + "\"";
         }
         return value;
     }

     private String translateDataObjectsForProcess(String processId) throws FileNotFoundException, UnsupportedEncodingException {
         if (processId == null) return "";
         List<DO> dataObjects = bpmnElements.getElementsByType(DO.class).stream()
                 .filter(d -> processId.equals(d.getProcessId()))
                 .sorted(Comparator.comparing(d -> d.getName() == null ? "" : d.getName()))
                 .collect(Collectors.toList());
         StringBuilder sb = new StringBuilder();
         for (DO d : dataObjects) {
             sb.append("\t\t").append(visit(d));
         }
         return sb.toString();
     }

     private static String defaultForType(String type) {
         if (type == null) return "null";
         switch (type.trim()) {
             case "Integer": case "int":     return "0";
             case "Long":    case "long":    return "0L";
             case "Double":  case "double":  return "0.0";
             case "Float":   case "float":   return "0.0f";
             case "Boolean": case "boolean": return "false";
             case "String":                  return "\"\"";
             default:                        return "null";
         }
     }
 
 } 






